apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spacy-deployment-en
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: spacy
        tier: backend
        lang: en
    spec:
      containers:
      - name: spacy
        image: olasearch/spacy_api:v5
        ports:
        - name: spacy-en-port
          containerPort: 9033
